spring.application.name=dapp-unq-grupo-r

spring.datasource.url=jdbc:postgresql://localhost:5432/dappfc
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

jwt.secret=dapp-unq-grupo-r-secret-key-2026-09-08-must-be-at-least-256-bit-long
jwt.expiration-ms=3600000
