spring.config.activate.on-profile=local
spring.datasource.url=jdbc:postgresql://localhost:5432/dappfc
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
